apiVersion: v1
kind: Service
metadata:
  name: kartoza-devops-app
  labels:
    app: kartoza-devops-app
spec:
  selector:
    app: kartoza-devops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: LoadBalancer
